# -*- coding: utf-8 -*-
"""Census_income.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhyKKz_Q5apBy0S3VH7ujrVou3kPnW19
"""

!pip install dmba
import dmba

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from dmba import plotDecisionTree, classificationSummary
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import matplotlib.pyplot as plt

census_income = pd.read_csv('adult.csv')

"""**1. Understanding the Dataset**"""

census_income.head()

census_income.shape

census_income.info()

census_income["income"].value_counts()
census_income["income"].value_counts(normalize=True) * 100

census_income.describe()

"""**GRAPHS - For data visualization**"""

import matplotlib.pyplot as plt

# Generate the Income Distribution Graph:

income_labels = census_income["income"].replace({
    0: "<=50K",
    1: ">50K"
})

income_labels.value_counts().plot(
    kind="pie",
    autopct="%1.1f%%",
    figsize=(6,6)
)

plt.title("Income Distribution")
plt.ylabel("")
plt.show()

# Generate the Age Distribution Graph:

plt.figure(figsize=(8,5))

census_income["age"].hist(
    bins=20,
    color="skyblue",
    edgecolor="black"
)

plt.axvspan(
    20, 50,
    alpha=0.2,
    color="orange",
    label="Main age concentration"
)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.legend()

plt.show()

# Generate the Education Distribution Graph:

edu_counts = census_income["education"].value_counts()

colors = ["orange" if i < 3 else "steelblue"
          for i in range(len(edu_counts))]

edu_counts.plot(
    kind="bar",
    color=colors,
    figsize=(10,5)
)

plt.title("Education Distribution")
plt.xlabel("Education Level")
plt.ylabel("Count")

plt.show()

# Generate the Marital Status Distribution Graph:

marital_counts = census_income["marital.status"].value_counts()

colors = [
    "orange" if x in ["Married-civ-spouse", "Never-married"]
    else "steelblue"
    for x in marital_counts.index
]

marital_counts.plot(
    kind="bar",
    color=colors,
    figsize=(10,5)
)

plt.title("Marital Status Distribution")
plt.xlabel("Marital Status")
plt.ylabel("Count")

plt.show()

# Generate the Hours Worked per Week Distribution Graph:

import matplotlib.pyplot as plt

mean_hours = census_income["hours.per.week"].mean()

plt.figure(figsize=(8,5))

census_income["hours.per.week"].hist(
    bins=20,
    color="lightgreen",
    edgecolor="black"
)

plt.axvline(
    mean_hours,
    color="red",
    linestyle="--",
    linewidth=2,
    label=f"Mean = {mean_hours:.1f}"
)

plt.title("Hours Worked per Week Distribution")
plt.xlabel("Hours Worked per Week")
plt.ylabel("Frequency")
plt.legend()

plt.show()

"""**2. Rename Columns**"""

census_income.columns = [c.replace('.', '_') for c in census_income.columns]

census_income.head()

"""**3. Identify Missing Values**"""

census_income.isnull().sum()

"""**4. Convert Missing Values**"""

# During the data cleaning process, we converted all "?" values to NaN
#so that Pandas could recognize them as missing values and handle them
# appropriately.

import numpy as np

census_income.replace("?", np.nan, inplace=True)

census_income.isna().sum()

# The dataset contains 488,415 total values (32,561 observations and 15 variables). After converting the "?" symbols to NaN, we identified 4,262
# missing values, representing approximately 0.87% of the dataset:

census_income.isna().sum()

"""**5. Handle Missing Values**"""

# The dataset contained missing values represented by the symbol "?". These values were converted to NaN and identified in three
# variables:

# - workclass: 1,836 missing values
# - occupation: 1,843 missing values
# - native_country: 583 missing values

# To preserve all observations, missing values were imputed using the mode (most frequent category) of each variable.

census_income["workclass"] = census_income["workclass"].fillna(
    census_income["workclass"].mode()[0]
)

census_income["occupation"] = census_income["occupation"].fillna(
    census_income["occupation"].mode()[0]
)

census_income["native_country"] = census_income["native_country"].fillna(
    census_income["native_country"].mode()[0]
)

# Validation:

census_income.isna().sum()

"""**6. Check for Duplicates**"""

census_income.duplicated().sum()

# Duplicate records were identified and removed:

census_income.drop_duplicates(inplace=True)

# Validation:

census_income.duplicated().sum()

"""**7. Remove Unnecessary or Redundant Variables**"""

# The variables 'education' and 'fnlwgt' were removed. 'education' contains
# the same information as 'education_num'.
# Keeping both variables would introduce redundant information.

census_income.drop(columns=["education"], inplace=True)
census_income.drop(columns=["fnlwgt"], inplace=True)

"""**8. Checking current variables**"""

census_income.columns.tolist()

"""**9. Prepare the Target Variable**"""

# Convert the target variable into a binary format because Logistic Regression requires the target variable to be
# represented numerically:

# 0 = income less than or equal to $50K
# 1 = income greater than $50K

census_income["income"] = census_income["income"].map({
    "<=50K": 0,
    ">50K": 1
})

"""**10. Encode Categorical Variables**"""

# Convert categorical variables into numeric values using category codes
# This allows machine learning models to process categorical data.

for col in census_income.select_dtypes(include=['object']).columns:
    census_income[col] = census_income[col].astype('category').cat.codes

"""**11. Separate Predictors and Target Variable**"""

# Creates the predictor dataset X by keeping all columns except the outcome variable income:

X = census_income.drop("income", axis=1)

# Selects income as the outcome variable that the logistic regression model will predict:

y = census_income["income"]

"""**12. Split Training and Testing Data**"""

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25, random_state=42)

"""**13. Standarization**"""

# Initialize the StandardScaler

scaler = StandardScaler()

# Scale training set
# Learns the scaling parameters from X_train and uses them to standardize the training predictors:
X_train_scaled = scaler.fit_transform(train_X)

# Converts the scaled training data from a NumPy array back into a pandas DataFrame:
X_train_scaled = pd.DataFrame(X_train_scaled)

# Scale testing set
# Uses the scaling parameters learned from the training data to standardize X_test.

X_test_scaled = scaler.transform(test_X)

# Converts the scaled test data from a NumPy array back into a pandas DataFrame.

X_test_scaled = pd.DataFrame(X_test_scaled)

"""**LOGISTIC REGRESSION MODEL**"""

logit_reg = LogisticRegression(max_iter=2000, class_weight='balanced', random_state=42)

# Trains the logistic regression model using the training predictors and training outcome values:

logit_reg.fit(X_train_scaled, train_y)

"""**Training data evaluation**"""

# LR Training data evaluation:

classificationSummary(train_y, logit_reg.predict(X_train_scaled))

"""**Testing data evaluation**

"""

# LR Testing data evaluation:

logit_pred = logit_reg.predict(X_test_scaled)

classificationSummary(test_y, logit_pred)

print("Accuracy:", accuracy_score(test_y, logit_pred))
print("Precision:", precision_score(test_y, logit_pred))
print("Recall:", recall_score(test_y, logit_pred))
print("F1 Score:", f1_score(test_y, logit_pred))
print("ROC-AUC:", roc_auc_score(test_y, logit_pred))

"""**DECISION TREE**"""

from sklearn.tree import DecisionTreeClassifier

# Create Decision Tree model:

dec_tree = DecisionTreeClassifier(random_state=1)

# Training the model:

dec_tree.fit(train_X, train_y)

"""**Training data evaluation**"""

# DT Training data evaluation:

classificationSummary(train_y, dec_tree.predict(train_X))

"""**Testing data evaluation**"""

# DT Testing data evaluation:

dec_tree_pred = dec_tree.predict(test_X)
classificationSummary(test_y, dec_tree_pred)

print("Accuracy:", accuracy_score(test_y, dec_tree_pred))
print("Precision:", precision_score(test_y, dec_tree_pred))
print("Recall:", recall_score(test_y, dec_tree_pred))
print("F1 Score:", f1_score(test_y, dec_tree_pred))
print("ROC-AUC:", roc_auc_score(test_y, dec_tree_pred))

"""Solving the overfitting issue with Depth = 10

"""

dectree_depth10 = DecisionTreeClassifier(max_depth=10, min_samples_leaf=50, class_weight='balanced', random_state=42)


# Trains the smaller decision tree on the training data:

dectree_depth10.fit(train_X, train_y)

# Plots the trained decision tree using the first two column names as features and the model's class labels.

plotDecisionTree(dectree_depth10,feature_names=train_X.columns,class_names=dectree_depth10.classes_)

# Training accuracy with maximum depth 10:

classificationSummary(train_y, dectree_depth10.predict(train_X))

# Testing accuracy with maximum depth 10:

dec_tree_pred10 = dectree_depth10.predict(test_X)

classificationSummary(test_y, dec_tree_pred10)

print("Accuracy:", accuracy_score(test_y, dec_tree_pred10))
print("Precision:", precision_score(test_y, dec_tree_pred10))
print("Recall:", recall_score(test_y, dec_tree_pred10))
print("F1 Score:", f1_score(test_y, dec_tree_pred10))
print("ROC-AUC:", roc_auc_score(test_y, dec_tree_pred10))

"""**RANDOM FOREST**"""

from sklearn.ensemble import RandomForestClassifier

# Creates a random-forest classifier containing 500 decision trees and fixes the random seed:

rf = RandomForestClassifier(n_estimators=500, max_depth=14, min_samples_leaf=5, class_weight='balanced', random_state=42)

# Trains the random-forest classifier on the training data:

rf.fit(train_X, train_y)

# RF Training data evaluation:

classificationSummary(train_y, rf.predict(train_X))

# RF Testing data evaluation:

rf_pred = rf.predict(test_X)

classificationSummary(test_y, rf_pred)

print("Accuracy:", accuracy_score(test_y, rf_pred))
print("Precision:", precision_score(test_y, rf_pred))
print("Recall:", recall_score(test_y, rf_pred))
print("F1 Score:", f1_score(test_y, rf_pred))
print("ROC-AUC:", roc_auc_score(test_y, rf_pred))

results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree', 'Tuned Decision Tree (Depth = 10)', 'Random Forest'],
    'Accuracy': [
        accuracy_score(test_y, logit_pred),
        accuracy_score(test_y, dec_tree_pred),
        accuracy_score(test_y, dec_tree_pred10),
        accuracy_score(test_y, rf_pred)
    ],
    'Precision': [
        precision_score(test_y, logit_pred),
        precision_score(test_y, dec_tree_pred),
        precision_score(test_y, dec_tree_pred10),
        precision_score(test_y, rf_pred)
    ],
    'Recall': [
        recall_score(test_y, logit_pred),
        recall_score(test_y, dec_tree_pred),
        recall_score(test_y, dec_tree_pred10),
        recall_score(test_y, rf_pred)
    ],
    'ROC-AUC': [
        roc_auc_score(test_y, logit_pred),
        roc_auc_score(test_y, dec_tree_pred),
        roc_auc_score(test_y, dec_tree_pred10),
        roc_auc_score(test_y, rf_pred)
    ]
})

# Create grouped bar chart
results.set_index('Model').plot(
    kind='bar',
    figsize=(10,6)
)

"""## Optional: KNN Model"""

from sklearn.neighbors import KNeighborsClassifier

# Train a classifier for different values of k
# Creates an empty list that will store the k value and accuracy from each model.
results = []
# Repeats the following indented steps for k values from 1 through 14.
for k in range(1, 15):
    # Creates and immediately trains a KNN classifier using the current value of k.
    knn = KNeighborsClassifier(n_neighbors=k).fit(X_train_scaled, train_y)
    # Adds a dictionary containing the current k value and its test accuracy to the results list.
    results.append({
        # Stores the current number of neighbors under the column name k.
        'k': k,
        # Predicts the test classes and calculates the accuracy for the current KNN model.
        'accuracy': accuracy_score(test_y, knn.predict(X_test_scaled))
    # Closes the dictionary and the append operation.
    })

# Convert results to a pandas data frame
# Converts the list of result dictionaries into a pandas DataFrame for easier comparison.
results = pd.DataFrame(results)
# Displays the table of k values and their corresponding test accuracies.
print(results)

knn = KNeighborsClassifier(n_neighbors=9)

knn.fit(X_train_scaled, train_y)

# KNN Training data evaluation:

classificationSummary(train_y, knn.predict(X_train_scaled))

# KNN Testing data evaluation:

classificationSummary(test_y, knn.predict(X_test_scaled))